#!/bin/bash

HERE=$PWD

repodiff() {
    "$HERE/../../scripts/repodiff" "$@"
}

run() {
    cargo run -q -- "$@"
}

rm -rf repo.git
mkdir repo.git
git -C repo.git init --bare --initial-branch master

rm -f ./*.ibundle
for rev in \
    'v7.0.001' \
    'v7.0.002' \
    'v7.0.003' \
    'v7.0.004' \
    'v7.0.005' \
    ; do

    git -C repo.git fetch -q "../$rev.git" --prune '*:*'
    (cd repo.git; run create "../$rev.ibundle")
done

rm -rf dest.git
mkdir dest.git
git -C dest.git init --bare

for i in *.ibundle; do
    rev="${i%.ibundle}"
    (
        cd dest.git
        run fetch "../$i"
        repodiff "../$rev".git .
    )
done
